"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarDays, Clock3, LayoutDashboard, Users, Scissors, Settings2, Plus, ExternalLink, ChevronLeft, ChevronRight, Ban } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";

type Service={id:string;name:string;description:string|null;duration_minutes:number|null;price_cents:number|null;notes:string|null;active:number;sort_order:number};
type Appointment={id:string;client_name:string;phone:string;email:string|null;service_name:string;service_id:string;day:string;start_minute:number;end_minute:number;status:string;notes:string|null;price_cents:number|null};
type Client={id:string;name:string;phone:string;email:string|null;notes:string|null;visits:number;last_visit:string|null};
type Hour={weekday:number;open_minute:number;close_minute:number;break_start:number|null;break_end:number|null;enabled:number};
type Block={id:string;day:string;start_minute:number;end_minute:number;reason:string|null;kind:string};
const weekdays=["Domingo","Segunda","Terça","Quarta","Quinta","Sexta","Sábado"];
const labels:Record<string,string>={confirmed:"Confirmado",pending:"Pendente",completed:"Concluído",cancelled:"Cancelado",no_show:"Não compareceu"};
const hm=(n:number|null)=>n===null?"":`${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`;
const fmt=(n:number|null)=>n===null?"A consultar":(n/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const api=async(action:string,body?:Record<string,unknown>):Promise<any>=>{const response=await fetch(body?"/api/admin":`/api/admin?action=${action}`,body?{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...body})}:undefined);const data=await response.json() as any;if(!response.ok)throw new Error(data.error??"Falha na operação");return data};

export default function AdminDashboard({email}:{email:string}){
  const [tab,setTab]=useState("overview"),[view,setView]=useState("day"),[focus,setFocus]=useState(today()),[appointments,setAppointments]=useState<Appointment[]>([]),[stats,setStats]=useState<Record<string,number>>({}),[popular,setPopular]=useState<{name:string;total:number}[]>([]),[services,setServices]=useState<Service[]>([]),[clients,setClients]=useState<Client[]>([]),[hours,setHours]=useState<Hour[]>([]),[blocks,setBlocks]=useState<Block[]>([]),[settings,setSettings]=useState<Record<string,string>>({}),[query,setQuery]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(false);
  const [editing,setEditing]=useState<Appointment|null>(null),[editingService,setEditingService]=useState<Service|null>(null),[editingClient,setEditingClient]=useState<Client|null>(null);
  const [blockDay,setBlockDay]=useState(today()),[blockStart,setBlockStart]=useState("09:00"),[blockEnd,setBlockEnd]=useState("10:00"),[blockReason,setBlockReason]=useState("");
  const range=useMemo(()=>{const date=new Date(`${focus}T12:00:00`);if(view==="week"){const day=date.getDay();const first=new Date(date);first.setDate(date.getDate()-day);const last=new Date(first);last.setDate(first.getDate()+6);return [first.toISOString().slice(0,10),last.toISOString().slice(0,10)]}if(view==="month")return [focus.slice(0,7)+"-01",focus.slice(0,7)+"-31"];return [focus,focus]},[focus,view]);
  const refresh=useCallback(async()=>{setLoading(true);try{const params=new URLSearchParams({start:range[0],end:range[1]});const response=await fetch(`/api/admin?${params}`);const data=await response.json() as any;if(!response.ok)throw new Error(data.error);setAppointments(data.appointments??[]);setStats(data.stats??{});setPopular(data.popular??[])}catch(e){setMessage(e instanceof Error?e.message:"Falha ao carregar agenda")}finally{setLoading(false)}},[range]);
  const loadTab=useCallback(async(next:string)=>{try{if(next==="services")setServices((await api("services")).services);if(next==="clients")setClients((await api("clients")).clients);if(next==="settings"){const [h,b]=await Promise.all([api("hours"),api("blocks")]);setHours(h.hours);setBlocks(b.blocks);setSettings(Object.fromEntries((h.settings??[]).map((s:{key:string;value:string})=>[s.key,s.value])))}}catch(e){setMessage(e instanceof Error?e.message:"Falha ao carregar dados")}},[]);
  useEffect(()=>{void refresh()},[refresh]);useEffect(()=>{void loadTab(tab)},[tab,loadTab]);
  const save=async(action:string,body:Record<string,unknown>,after?:()=>void)=>{setMessage("");try{await api(action,body);setMessage("Alterações salvas com sucesso.");after?.();void refresh();void loadTab(tab)}catch(e){setMessage(e instanceof Error?e.message:"Falha ao salvar")}};
  const move=(direction:number)=>{const date=new Date(`${focus}T12:00:00`);date.setDate(date.getDate()+direction*(view==="week"?7:view==="month"?30:1));setFocus(date.toISOString().slice(0,10))};
  return <main className="admin-page"><aside className="admin-sidebar"><a href="/" className="brand"><span className="brand-script">Pérola Leite</span><span className="brand-sub">PAINEL DO STUDIO</span></a><div className="admin-nav">{[["overview",LayoutDashboard,"Visão geral"],["calendar",CalendarDays,"Agenda"],["services",Scissors,"Serviços"],["clients",Users,"Clientes"],["settings",Settings2,"Configurações"]].map(([id,Icon,label])=><button key={id as string} onClick={()=>setTab(id as string)} className={tab===id?"active":""}><Icon size={18}/>{label as string}</button>)}</div><a href="/agendar" className="admin-new"><Plus size={17}/> Novo agendamento</a><div className="admin-account">{email}<br/><a href="/">Ver site <ExternalLink size={12}/></a></div></aside>
    <section className="admin-main"><header className="admin-top"><div><span className="eyebrow">STUDIO PÉROLA LEITE</span><h1>{({overview:"Visão geral",calendar:"Agenda",services:"Serviços",clients:"Clientes",settings:"Configurações"} as Record<string,string>)[tab]}</h1></div><span>{new Date().toLocaleDateString("pt-BR",{day:"numeric",month:"long",year:"numeric"})}</span></header>{message&&<div className="admin-message" role="status">{message}<button onClick={()=>setMessage("")}>×</button></div>}
    {tab==="overview"&&<><div className="stat-grid"><div><span>Agendamentos hoje</span><strong>{stats.today??0}</strong><CalendarDays size={22}/></div><div><span>Próximos</span><strong>{stats.upcoming??0}</strong><Clock3 size={22}/></div><div><span>Clientes</span><strong>{stats.clients??0}</strong><Users size={22}/></div><div><span>Cancelamentos</span><strong>{stats.cancelled??0}</strong><Ban size={22}/></div></div><div className="admin-card"><div className="admin-card-head"><h2>Agenda do dia</h2><button onClick={()=>setTab("calendar")}>Ver agenda completa →</button></div><AppointmentList appointments={appointments.filter(a=>a.day===today())} onEdit={setEditing}/></div><div className="admin-card"><h2>Serviços mais agendados</h2><div className="admin-list">{popular.map(p=><div className="popular-row" key={p.name}><span>{p.name}</span><strong>{p.total}</strong></div>)}</div></div></>}
    {tab==="calendar"&&<><div className="calendar-toolbar"><div><Button variant={view==="day"?"default":"outline"} onClick={()=>setView("day")}>Dia</Button><Button variant={view==="week"?"default":"outline"} onClick={()=>setView("week")}>Semana</Button><Button variant={view==="month"?"default":"outline"} onClick={()=>setView("month")}>Mês</Button></div><div><Button variant="outline" onClick={()=>move(-1)}><ChevronLeft/></Button><Input type="date" value={focus} onChange={e=>setFocus(e.target.value)}/><Button variant="outline" onClick={()=>move(1)}><ChevronRight/></Button></div></div><div className="admin-card"><div className="admin-card-head"><h2>{view==="day"?new Date(`${focus}T12:00:00`).toLocaleDateString("pt-BR",{weekday:"long",day:"numeric",month:"long"}):`${range[0]} a ${range[1]}`}</h2><a href="/agendar">+ Novo agendamento</a></div>{loading?<p>Carregando agenda...</p>:<AppointmentList appointments={appointments} onEdit={setEditing}/>}</div></>}
    {tab==="services"&&<div className="admin-card"><div className="admin-card-head"><h2>Catálogo de serviços</h2><Button onClick={()=>setEditingService({id:"",name:"",description:"",duration_minutes:null,price_cents:null,notes:"",active:1,sort_order:services.length})}><Plus/> Adicionar</Button></div><p className="admin-help">Configure duração e dias de atendimento para abrir a reserva online. Valores não informados aparecem como “a consultar”.</p><div className="admin-list">{services.map(s=><button className="admin-list-row" key={s.id} onClick={()=>setEditingService(s)}><strong>{s.name}</strong><span>{s.duration_minutes?`${s.duration_minutes} min`:"Sem duração"} · {fmt(s.price_cents)} · {s.active?"Ativo":"Inativo"}</span><span>Editar →</span></button>)}</div></div>}
    {tab==="clients"&&<div className="admin-card"><div className="admin-card-head"><h2>Clientes</h2><Input className="client-search" placeholder="Buscar nome ou telefone" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="admin-list">{clients.filter(c=>`${c.name} ${c.phone}`.toLowerCase().includes(query.toLowerCase())).map(c=><button className="admin-list-row" key={c.id} onClick={()=>setEditingClient(c)}><strong>{c.name}</strong><span>{c.phone} · {c.visits} visita(s)</span><span>Detalhes →</span></button>)}</div>{!clients.length&&<p className="admin-help">As clientes aparecem aqui após o primeiro agendamento.</p>}</div>}
    {tab==="settings"&&<div className="settings-grid"><div className="admin-card"><h2>Horários de atendimento</h2><p className="admin-help">Ative somente os dias e horários reais do Studio.</p>{weekdays.map((label,day)=>{const h=hours.find(x=>x.weekday===day);return <HourEditor key={day} label={label} day={day} hour={h} onSave={body=>save("hours",body)}/>})}</div><div className="admin-card"><h2>Intervalos e contato</h2><SettingRow label="Intervalo entre clientes (min)" value={settings.buffer_minutes??"0"} onSave={value=>save("setting",{key:"buffer_minutes",value})}/><SettingRow label="Passo dos horários (min)" value={settings.slot_step_minutes??"30"} onSave={value=>save("setting",{key:"slot_step_minutes",value})}/><SettingRow label="WhatsApp do Studio" value={settings.whatsapp??""} onSave={value=>save("setting",{key:"whatsapp",value})}/><h2 style={{marginTop:35}}>Bloqueios e folgas</h2><div className="block-form"><Input type="date" value={blockDay} onChange={e=>setBlockDay(e.target.value)}/><Input type="time" value={blockStart} onChange={e=>setBlockStart(e.target.value)}/><Input type="time" value={blockEnd} onChange={e=>setBlockEnd(e.target.value)}/><Input placeholder="Motivo opcional" value={blockReason} onChange={e=>setBlockReason(e.target.value)}/><Button onClick={()=>save("block",{day:blockDay,startMinute:blockStart,endMinute:blockEnd,reason:blockReason})}>Bloquear período</Button></div><div className="admin-list">{blocks.map(b=><div className="admin-list-row" key={b.id}><strong>{b.day} · {hm(b.start_minute)}–{hm(b.end_minute)}</strong><span>{b.reason}</span><button onClick={()=>save("unblock",{id:b.id})}>Remover</button></div>)}</div><h2 style={{marginTop:35}}>Sinal para reserva</h2><p className="admin-help">Configuração preparada para uma futura integração de pagamento. Nenhuma cobrança é realizada por este site agora.</p><SettingRow label="Modo (none, fixed ou percent)" value={settings.deposit_mode??"none"} onSave={value=>save("setting",{key:"deposit_mode",value})}/><SettingRow label="Valor em centavos ou percentual" value={settings.deposit_value??"0"} onSave={value=>save("setting",{key:"deposit_value",value})}/></div></div>}
    </section>
    {editing&&<div className="admin-modal-backdrop" onClick={()=>setEditing(null)}><div className="admin-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setEditing(null)}>×</button><h2>Agendamento</h2><p>{editing.client_name} · {editing.phone}</p><p>{editing.service_name} · {fmt(editing.price_cents)}</p><label>Data<Input type="date" defaultValue={editing.day} id="edit-day"/></label><label>Horário<Input type="time" defaultValue={hm(editing.start_minute)} id="edit-time"/></label><label>Status<select defaultValue={editing.status} id="edit-status">{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Observações<Textarea defaultValue={editing.notes??""} id="edit-notes"/></label><Button onClick={()=>{const get=(id:string)=>(document.getElementById(id) as HTMLInputElement).value;void save("appointment",{id:editing.id,day:get("edit-day"),startMinute:get("edit-time"),status:get("edit-status"),notes:get("edit-notes")},()=>setEditing(null))}}>Salvar alterações</Button><a href={`https://wa.me/55${editing.phone.replace(/\D/g,"")}`} target="_blank" rel="noreferrer">Conversar pelo WhatsApp ↗</a></div></div>}
    {editingService&&<div className="admin-modal-backdrop" onClick={()=>setEditingService(null)}><div className="admin-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setEditingService(null)}>×</button><h2>Editar serviço</h2><ServiceEditor service={editingService} onSave={body=>save("service",body,()=>setEditingService(null))}/></div></div>}
    {editingClient&&<div className="admin-modal-backdrop" onClick={()=>setEditingClient(null)}><div className="admin-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setEditingClient(null)}>×</button><h2>{editingClient.name}</h2><p>{editingClient.phone} · {editingClient.email||"Sem e-mail"}</p><p>{editingClient.visits} visita(s) · Último atendimento: {editingClient.last_visit||"—"}</p><ClientHistory id={editingClient.id}/><label>Observações internas<Textarea defaultValue={editingClient.notes??""} id="client-notes"/></label><Button onClick={()=>void save("client",{id:editingClient.id,notes:(document.getElementById("client-notes") as HTMLTextAreaElement).value},()=>setEditingClient(null))}>Salvar observações</Button><a href={`https://wa.me/55${editingClient.phone.replace(/\D/g,"")}`} target="_blank" rel="noreferrer">Conversar pelo WhatsApp ↗</a></div></div>}
  </main>;
}
function AppointmentList({appointments,onEdit}:{appointments:Appointment[];onEdit:(a:Appointment)=>void}){return appointments.length?<div className="appointment-list">{appointments.map(a=><button className="appointment-row" key={a.id} onClick={()=>onEdit(a)}><span className="appointment-time">{a.day}<br/><strong>{hm(a.start_minute)}</strong></span><span><strong>{a.client_name}</strong><small>{a.service_name} · {hm(a.end_minute)}</small></span><span className={`status status-${a.status}`}>{labels[a.status]}</span><span>→</span></button>)}</div>:<div className="admin-empty">Nenhum agendamento nesse período.</div>}
function HourEditor({label,day,hour,onSave}:{label:string;day:number;hour?:Hour;onSave:(v:Record<string,unknown>)=>void}){const [open,setOpen]=useState(hm(hour?.open_minute??540)),[close,setClose]=useState(hm(hour?.close_minute??1080)),[start,setStart]=useState(hm(hour?.break_start??null)),[end,setEnd]=useState(hm(hour?.break_end??null)),[enabled,setEnabled]=useState(!!hour?.enabled);useEffect(()=>{setOpen(hm(hour?.open_minute??540));setClose(hm(hour?.close_minute??1080));setStart(hm(hour?.break_start??null));setEnd(hm(hour?.break_end??null));setEnabled(!!hour?.enabled)},[hour]);return <div className="hour-row"><strong>{label}</strong><Switch checked={enabled} onCheckedChange={setEnabled} aria-label={`Atender ${label}`}/><Input type="time" value={open} onChange={e=>setOpen(e.target.value)} disabled={!enabled}/><Input type="time" value={close} onChange={e=>setClose(e.target.value)} disabled={!enabled}/><Input type="time" value={start} onChange={e=>setStart(e.target.value)} disabled={!enabled} title="Início do intervalo"/><Input type="time" value={end} onChange={e=>setEnd(e.target.value)} disabled={!enabled} title="Fim do intervalo"/><button onClick={()=>onSave({weekday:day,openMinute:open,closeMinute:close,breakStart:start||null,breakEnd:end||null,enabled})}>Salvar</button></div>}
function SettingRow({label,value,onSave}:{label:string;value:string;onSave:(value:string)=>void}){const [text,setText]=useState(value);useEffect(()=>setText(value),[value]);return <div className="setting-row"><label>{label}<Input value={text} onChange={e=>setText(e.target.value)}/></label><Button variant="outline" onClick={()=>onSave(text)}>Salvar</Button></div>}
function ServiceEditor({service,onSave}:{service:Service;onSave:(body:Record<string,unknown>)=>void}){const [name,setName]=useState(service.name),[description,setDescription]=useState(service.description??""),[duration,setDuration]=useState(service.duration_minutes?.toString()??""),[price,setPrice]=useState(service.price_cents===null?"":(service.price_cents/100).toFixed(2)),[notes,setNotes]=useState(service.notes??""),[active,setActive]=useState(!!service.active);return <div className="modal-form"><label>Nome<Input value={name} onChange={e=>setName(e.target.value)}/></label><label>Descrição<Textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Duração em minutos<Input type="number" min="15" value={duration} onChange={e=>setDuration(e.target.value)}/></label><label>Valor em R$ (deixe vazio se não informado)<Input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Observações<Textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><label className="switch-line">Serviço ativo <Switch checked={active} onCheckedChange={setActive}/></label><Button onClick={()=>onSave({id:service.id,name,description,durationMinutes:duration,priceCents:price===""?null:Math.round(Number(price)*100),notes,active,sortOrder:service.sort_order})}>Salvar serviço</Button></div>}
function ClientHistory({id}:{id:string}){const [history,setHistory]=useState<{id:string;day:string;start_minute:number;status:string;service_name:string}[]>([]);useEffect(()=>{fetch(`/api/admin?action=client-history&id=${encodeURIComponent(id)}`).then(r=>r.json() as Promise<any>).then(data=>setHistory(data.history??[])).catch(()=>{})},[id]);return <div className="client-history"><strong>Histórico</strong>{history.length?history.map(h=><p key={h.id}>{h.day} · {hm(h.start_minute)} · {h.service_name} · {labels[h.status]}</p>):<p>Nenhum atendimento registrado.</p>}</div>}
