import { sqliteTable, text, integer, index } from "drizzle-orm/sqlite-core";

export const admins = sqliteTable("admins", { id: text("id").primaryKey(), email: text("email").notNull().unique(), createdAt: text("created_at").notNull() });
export const clients = sqliteTable("clients", { id: text("id").primaryKey(), name: text("name").notNull(), phone: text("phone").notNull().unique(), email: text("email"), notes: text("notes"), createdAt: text("created_at").notNull() });
export const services = sqliteTable("services", { id: text("id").primaryKey(), name: text("name").notNull(), description: text("description"), priceCents: integer("price_cents"), durationMinutes: integer("duration_minutes"), image: text("image"), notes: text("notes"), active: integer("active", { mode:"boolean" }).notNull().default(true), sortOrder: integer("sort_order").notNull().default(0) });
export const appointments = sqliteTable("appointments", { id: text("id").primaryKey(), clientId: text("client_id").notNull().references(()=>clients.id), serviceId: text("service_id").notNull().references(()=>services.id), day: text("day").notNull(), startMinute: integer("start_minute").notNull(), endMinute: integer("end_minute").notNull(), status: text("status").notNull().default("confirmed"), notes: text("notes"), priceCents: integer("price_cents"), createdAt: text("created_at").notNull(), updatedAt: text("updated_at").notNull() }, t=>[index("idx_appointments_day_status").on(t.day,t.status),index("idx_appointments_client").on(t.clientId)]);
export const businessHours = sqliteTable("business_hours", { weekday: integer("weekday").primaryKey(), openMinute: integer("open_minute").notNull(), closeMinute: integer("close_minute").notNull(), breakStart: integer("break_start"), breakEnd: integer("break_end"), enabled: integer("enabled", {mode:"boolean"}).notNull().default(false) });
export const blockedTimes = sqliteTable("blocked_times", { id: text("id").primaryKey(), day: text("day").notNull(), startMinute: integer("start_minute").notNull(), endMinute: integer("end_minute").notNull(), reason: text("reason"), kind: text("kind").notNull().default("block") }, t=>[index("idx_blocked_times_day").on(t.day)]);
export const settings = sqliteTable("settings", { key: text("key").primaryKey(), value: text("value").notNull() });
export const notificationJobs = sqliteTable("notification_jobs", { id: text("id").primaryKey(), appointmentId: text("appointment_id").notNull().references(()=>appointments.id), kind: text("kind").notNull(), channel: text("channel").notNull(), scheduledAt: text("scheduled_at").notNull(), status: text("status").notNull().default("awaiting_provider"), sentAt: text("sent_at"), error: text("error") }, t=>[index("idx_notification_jobs_schedule_status").on(t.status,t.scheduledAt)]);
