"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Image from "next/image";
import { apiFetch, siteHref } from "@/lib/client-runtime";
import { cachedDaySlots, invalidateCalendar, loadCalendarMonth } from "@/lib/booking-calendar-client";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, Clock3, CalendarDays, MapPin } from "lucide-react";
import { Calendar } from "@/components/ui/calendar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { ptBR } from "date-fns/locale";

type Service={id:string;name:string;description:string|null;price_cents:number|null;duration_minutes:number|null;image:string|null;notes:string|null;price_is_demo?:boolean};
type ReservationCalendar={ics:string;googleUrl:string;start:string;end:string;timeZone:string};
type Slot={minute:number;label:string};
type PublicApiResponse={services?:Service[];whatsapp?:string;days?:string[];slots?:Slot[];error?:string};
const key=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const monthKey=(date:Date)=>key(date).slice(0,7);
const displayDate=(day:string)=>new Date(`${day}T12:00:00`).toLocaleDateString("pt-BR",{weekday:"long",day:"numeric",month:"long",year:"numeric"});
const money=(cents:number|null)=>cents===null?"Valor a consultar":(cents/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const minutes=(value:number|null)=>value===null?"Duração a definir":`${Math.floor(value/60)?`${Math.floor(value/60)}h`:""}${value%60?`${String(value%60).padStart(2,"0")}min`:""}`;

export default function Booking(){
  const [services,setServices]=useState<Service[]>([]),[whatsapp,setWhatsapp]=useState("");
  const [loading,setLoading]=useState(true),[loadingDays,setLoadingDays]=useState(false),[loadingSlots,setLoadingSlots]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const [step,setStep]=useState(0),[serviceId,setServiceId]=useState(""),[month,setMonth]=useState(new Date()),[days,setDays]=useState<string[]>([]),[day,setDay]=useState(""),[slots,setSlots]=useState<Slot[]>([]),[slot,setSlot]=useState<number|null>(null);
  const [name,setName]=useState(""),[phone,setPhone]=useState(""),[email,setEmail]=useState(""),[notes,setNotes]=useState(""),[bookingId,setBookingId]=useState("");
  const visibleMonth=monthKey(month);
  const service=useMemo(()=>services.find(s=>s.id===serviceId),[services,serviceId]);
  const [calendar,setCalendar]=useState<ReservationCalendar|null>(null);
  const downloadCalendar=()=>{if(!calendar)return;const url=URL.createObjectURL(new Blob([calendar.ics],{type:"text/calendar;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`studio-perola-${bookingId.slice(0,8)}.ics`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
  useEffect(()=>{apiFetch("/api/public").then(async r=>{const data=await r.json() as PublicApiResponse;if(!r.ok)throw new Error(data.error??"Falha ao carregar serviços");return data}).then(data=>{const list=data.services??[];setServices(list);setWhatsapp(data.whatsapp??"");if(list[0]?.duration_minutes)void loadCalendarMonth(list[0].id,monthKey(new Date())).catch(()=>{});const id=new URLSearchParams(window.location.search).get("servico");if(id&&list.some((s:Service)=>s.id===id)){setServiceId(id);setStep(1)}}).catch(()=>setError("Não foi possível carregar os serviços. Atualize a página." )).finally(()=>setLoading(false))},[]);
  useEffect(()=>{if(!serviceId)return;let live=true;setDays([]);setLoadingDays(true);loadCalendarMonth(serviceId,visibleMonth).then(data=>{if(live){setDays(data.days);const next=new Date(`${visibleMonth}-01T12:00:00`);next.setMonth(next.getMonth()+1);void loadCalendarMonth(serviceId,monthKey(next)).catch(()=>{})}}).catch(()=>{if(live)setError("Não foi possível carregar as datas disponíveis.")}).finally(()=>{if(live)setLoadingDays(false)});return()=>{live=false}},[serviceId,visibleMonth]);
  useEffect(()=>{if(!day||!serviceId)return;const cached=cachedDaySlots(serviceId,day);if(cached){setSlots(cached);setLoadingSlots(false);return}let live=true;setSlots([]);setLoadingSlots(true);apiFetch(`/api/calendar?service=${encodeURIComponent(serviceId)}&day=${day}`).then(async r=>{const data=await r.json() as PublicApiResponse;if(!r.ok)throw new Error(data.error??"Falha ao carregar horários");return data}).then(data=>{if(live)setSlots(data.slots??[])}).catch(()=>{if(live)setError("Não foi possível carregar os horários.")}).finally(()=>{if(live)setLoadingSlots(false)});return()=>{live=false}},[day,serviceId]);
  const selectService=(id:string)=>{setServiceId(id);setDay("");setSlot(null);setError("");setStep(1)};
  const selectDay=(date:Date|undefined)=>{if(!date)return;setDay(key(date));setSlot(null);setError("")};
  const submit=useCallback(async()=>{
    if(!service||!day||slot===null||!name.trim()||phone.replace(/\D/g,"").length<10){setError("Informe seu nome e um telefone válido.");return}
    setBusy(true);setError("");
    try{const response=await apiFetch("/api/public",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({serviceId:service.id,day,minute:slot,name,phone,email,notes})});const result=await response.json() as any;if(!response.ok)throw new Error(result.error??"Falha ao reservar horário.");invalidateCalendar(service.id,day);setBookingId(result.id);setCalendar(result.calendar??null);setStep(5)}catch(e){invalidateCalendar(service.id,day);setError(e instanceof Error?e.message:"Falha ao reservar horário.");if(step===4)setStep(3)}finally{setBusy(false)}
  },[service,day,slot,name,phone,email,notes,step]);
  useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{void Promise.resolve(context.registerTool({name:"start_booking",title:"Iniciar agendamento",description:"Seleciona um serviço e inicia o fluxo visível de agendamento.",inputSchema:{type:"object",properties:{serviceId:{type:"string"}},required:["serviceId"],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const id=(input as {serviceId?:string})?.serviceId;if(!id||!services.some(s=>s.id===id))throw new Error("Serviço inválido");selectService(id);return {serviceId:id,step:"date"}}},{signal:controller.signal})).catch(()=>{})}catch{}return()=>controller.abort()},[services]);
  const whatsappUrl=whatsapp?`https://wa.me/${whatsapp.replace(/\D/g,"")}?text=${encodeURIComponent(`Olá! Acabei de realizar meu agendamento para ${service?.name} no dia ${day}, às ${slots.find(s=>s.minute===slot)?.label}.`)}`:"";
  return <main className="booking-page"><header className="booking-header shell"><a href={siteHref("/")} className="brand"><span className="brand-script">Pérola Leite</span><span className="brand-sub">NAIL DESIGNER · LAVRAS, MG</span></a><a href={siteHref("/")} className="booking-back"><ArrowLeft size={17}/> Voltar ao site</a></header>
    <div className="booking-layout shell"><aside className="booking-aside"><span className="eyebrow">AGENDE SEU MOMENTO</span><h1>Seu cuidado começa <em>aqui.</em></h1><p>Escolha o serviço, encontre um horário e confirme em poucos passos.</p><div className="booking-aside-image"><Image src="/images/vinho-sem-icone.png" alt="Unhas com esmaltação em tom vinho do Studio Pérola Leite" fill sizes="(max-width: 800px) 100vw, 28vw"/></div><div className="booking-address"><MapPin size={18}/> Rua Evaristo Alves, 110 · Lavras, MG</div></aside>
    <section className="booking-panel" aria-live="polite"><div className="booking-progress"><span>AGENDAMENTO ONLINE</span><span>{step===5?"CONCLUÍDO":`PASSO ${Math.min(step+1,5)} DE 5`}</span></div><div className="progress-track"><span style={{width:`${step===5?100:(step+1)*20}%`}}/></div><ol className="booking-step-labels" aria-label="Etapas do agendamento">{["Serviço","Data","Horário","Dados","Confirmar"].map((label,index)=><li key={label} className={index===Math.min(step,4)?"current":index<step?"done":""}>{label}</li>)}</ol>
    <div key={step} className="booking-step-content">
    {loading?<div className="booking-empty" role="status">Carregando serviços...</div>:step===0?<><div className="booking-title"><h2>Qual serviço você deseja?</h2><p>Selecione o procedimento para continuar.</p>{services.some(s=>s.price_is_demo)&&<p className="demo-price-note">Preços fictícios de demonstração. Confirme os valores com o Studio antes do atendimento.</p>}</div><div className="booking-services">{services.map(s=><button key={s.id} className="booking-service" onClick={()=>selectService(s.id)}><span className="booking-service-image">{s.image&&<Image src={s.image} alt="" fill sizes="72px"/>}</span><span className="booking-service-copy"><strong>{s.name}</strong><small>{s.duration_minutes?minutes(s.duration_minutes):"Duração a confirmar"} · {money(s.price_cents)}{s.price_is_demo?" · fictício":""}</small></span><ArrowRight size={18}/></button>)}</div>{!services.length&&!error&&<p>Nenhum serviço cadastrado no momento.</p>}</>:
    step===1?<><div className="booking-title"><button className="step-back" onClick={()=>setStep(0)}><ArrowLeft size={16}/> Alterar serviço</button><h2>Escolha o melhor dia</h2><p>{service?.name}</p></div>{!service?.duration_minutes?<div className="booking-empty">Este serviço ainda não tem duração cadastrada. A profissional precisa configurá-la antes de abrir horários.</div>:<><Calendar mode="single" locale={ptBR} selected={day?new Date(`${day}T12:00:00`):undefined} onSelect={selectDay} month={month} onMonthChange={setMonth} disabled={date=>!days.includes(key(date))} showOutsideDays={false} className="booking-calendar"/>{loadingDays?<p className="calendar-hint" role="status">Buscando dias disponíveis...</p>:<p className="calendar-hint">{days.length?"Apenas dias com horários disponíveis podem ser selecionados.":"Nenhum dia disponível neste mês. Consulte o próximo mês."}</p>}{day&&<Button onClick={()=>setStep(2)} className="wide-button">Ver horários <ArrowRight/></Button>}</>}</>:
    step===2?<><div className="booking-title"><button className="step-back" onClick={()=>setStep(1)}><ArrowLeft size={16}/> Alterar data</button><h2>Escolha seu horário</h2><p>{displayDate(day)}</p></div><div className="slots-grid">{slots.map(s=><button key={s.minute} className={slot===s.minute?"slot active":"slot"} aria-pressed={slot===s.minute} onClick={()=>setSlot(s.minute)}><Clock3 size={16}/>{s.label}</button>)}</div>{!slots.length&&<div className="booking-empty" role="status">{loadingSlots?"Buscando horários disponíveis...":"Sem horários livres nesse dia. Escolha outra data."}</div>}{slot!==null&&<Button className="wide-button" onClick={()=>setStep(3)}>Continuar <ArrowRight/></Button>}</>:
    step===3?<><div className="booking-title"><button className="step-back" onClick={()=>setStep(2)}><ArrowLeft size={16}/> Alterar horário</button><h2>Seus dados</h2><p>Precisamos apenas do essencial para sua reserva.</p></div><div className="booking-form"><label>Nome completo *<Input value={name} onChange={e=>setName(e.target.value)} maxLength={100} autoComplete="name" placeholder="Como podemos chamar você?"/></label><label>WhatsApp / telefone *<Input value={phone} onChange={e=>setPhone(e.target.value)} maxLength={20} inputMode="tel" autoComplete="tel" placeholder="(00) 00000-0000"/></label><label>E-mail (opcional)<Input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" placeholder="voce@exemplo.com"/></label><label>Observações (opcional)<Textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={500} placeholder="Conte algum detalhe importante"/></label><Button className="wide-button" onClick={()=>{if(name.trim()&&phone.replace(/\D/g,"").length>=10){setError("");setStep(4)}else setError("Informe seu nome e um telefone válido.")}}>Revisar agendamento <ArrowRight/></Button></div></>:
    step===4?<><div className="booking-title"><button className="step-back" onClick={()=>setStep(3)}><ArrowLeft size={16}/> Alterar dados</button><h2>Confirme os detalhes</h2><p>Confira tudo antes de reservar.</p></div><div className="summary"><div><span>Serviço</span><strong>{service?.name}</strong></div><div><span>Data</span><strong>{displayDate(day)}</strong></div><div><span>Horário</span><strong>{slots.find(s=>s.minute===slot)?.label}</strong></div><div><span>Duração</span><strong>{minutes(service?.duration_minutes??null)}</strong></div><div><span>Valor</span><strong>{money(service?.price_cents??null)}{service?.price_is_demo?" (fictício)":""}</strong></div><div><span>Cliente</span><strong>{name} · {phone}</strong></div>{email&&<div><span>E-mail</span><strong>{email}</strong></div>}</div>{service?.price_is_demo&&<p className="demo-price-note">Este valor é fictício e serve apenas para demonstração. Confirme o preço real com o Studio.</p>}<Button className="wide-button" disabled={busy} onClick={submit}>{busy?"Confirmando...":"Confirmar agendamento"} <Check size={18}/></Button></>:
    <div className="booking-success"><CheckCircle2 size={54}/><span className="eyebrow">HORÁRIO RESERVADO</span><h2>Seu momento está marcado!</h2><p>{service?.name}<br/>{displayDate(day)} às {slots.find(s=>s.minute===slot)?.label}</p><small>Referência: {bookingId.slice(0,8).toUpperCase()}</small>{service?.price_is_demo&&<p className="demo-price-note">Valor fictício: {money(service.price_cents)}. Confirme o preço real com o Studio.</p>}{calendar&&<div className="calendar-export-actions"><a href={calendar.googleUrl} target="_blank" rel="noreferrer" className="calendar-export"><CalendarDays size={18}/>Adicionar ao Google Calendar</a><button type="button" className="calendar-export" onClick={downloadCalendar}><CalendarDays size={18}/>Baixar calendário (.ics)</button><small>O arquivo pode ser importado no calendário do celular, Outlook ou Apple Calendar.</small></div>}{whatsappUrl&&<a className="button-main" href={whatsappUrl} target="_blank" rel="noreferrer">Abrir conversa no WhatsApp</a>}<a href={siteHref("/")}>Voltar ao início</a></div>}
    </div>
    {error&&<div role="alert" className="booking-error">{error}</div>}
    </section></div></main>;
}


